### PR TITLE
feat: travis tests

### LINKED ISSUE #309: Travis Tests

### PR DESCRIPTION
**Pull request by odinuv**
fixes #309
replaces https://github.com/keboola/docker-bundle/pull/312

### CODE REVIEW

**Comment by odinuv** [comment]
image

28 minut!

**Comment by odinuv** [comment]
akorat jsem musel vypnout buildovani branchi, aby se nespoustely soubezne testy na PR a branch, nebo by mozna slo nastavit job concurrency na 3?

**Comment by ondrejhlavacek** [comment]
hm, ta job concurrency se může úplně stejně pomlátit i když to bude na 3. pošleš commit do PR a nevíš, v jakým pořadí se bude pouštět branch/pr test. buď jak píšeš, a nebo jako to je v connection přes `parallel`

**Comment by odinuv** [comment]
no pres ten parallel zase nevim jak udelat sber code coverage, pak je jeste parallelphpunit, ale to zase nejede na php 5, taky to muzem uplne vypnout a nechat to bezet hodinu, se nepotentujem a pripraveny na parallel to zustane.

**Comment by ondrejhlavacek** [comment]
sběr code coverage by proběhl stejně jako teď, jen bys to poslal v každým subtasku do jinýho 
`build/logs/clover.xml` souboru, odkud by si to cc-test-reporter převzal

**Comment by odinuv** [comment]
jj, na controller a command testy jsem nesahal

**Comment by odinuv** [comment]
V poslednim master buildu https://jenkins.keboola.com/view/Docker%20Runner/job/PHPUnit%20-%20docker-bundle/685/console je
287 / 1077 (tests/assertions)

travis build ma:
job 1 https://travis-ci.org/keboola/docker-bundle/jobs/389526101:
110 / 349
job 2 https://travis-ci.org/keboola/docker-bundle/jobs/389526102:
97 / 295
job 3 https://travis-ci.org/keboola/docker-bundle/jobs/389526103
19 / 160
= celkem 226 / 804

na jenkinsu zbyvaji controller + command testy:
command: 2 / 15
controller: 52 / 175
= 54 / 190

vsechny testy v branchi:
= 280 / 994

odstranenene testy:
- https://github.com/keboola/docker-bundle/pull/314/commits/cd48ef6b9a63733fa9d2734df0b4cc58ef8ae10b 
1 / 2

- https://github.com/keboola/docker-bundle/pull/314/commits/e6665cf370f7699b679effb9827aef6529cce49e
1 / 2

- storage api reader https://github.com/keboola/docker-bundle/pull/314/commits/e342fba838bdf8613e1c92d66f12b9114c093753, https://github.com/keboola/docker-bundle/pull/314/commits/05b7ecf72ecabcd98d44056f7ec2df6c1e1dd12d,
https://github.com/keboola/docker-bundle/pull/314/commits/d2a906ed2576420a7607661e4f50db917bad629b,
3 / 8

- storage api writer https://github.com/keboola/docker-bundle/pull/314/commits/f590398baf3561c025e8deb2b8e854206277d867,
https://github.com/keboola/docker-bundle/pull/314/commits/22fe611a131aabac72382bd6225d8454c15c67ef,
https://github.com/keboola/docker-bundle/pull/314/commits/6028e39772344426bf4ac4d17ae20d1f62049e10
3 / 21

= celkem odstranene:
8 / 33

= celkem
288 / 1027

jeden test pridany https://github.com/keboola/docker-bundle/pull/314/commits/62863273050399827777cccfe9ac6276c0576ac8
1 / 2

takze pocet testu souhlasi, je tam o 52 min assertions
nejaky assertions se ztratily v techto commitech:
https://github.com/keboola/docker-bundle/pull/312/commits/d301c236c7b3b4b8ff3541073eaa0e39629d2fe7 https://github.com/keboola/docker-bundle/pull/312/commits/c252df27ee5f2ea9a382bc6f6ae5171f1f8ec52e https://github.com/keboola/docker-bundle/pull/312/commits/29568e13b863e6aab91032957dd3f9460b67872a https://github.com/keboola/docker-bundle/pull/312/commits/14fe998643ad6e273ea043283964b1dc98ed3ac3 https://github.com/keboola/docker-bundle/pull/312/commits/8d1164826447e45c116b88b944420607ca4e9820 https://github.com/keboola/docker-bundle/pull/312/commits/b45900459ae0dcc147654e7ef091225d05a61c3e https://github.com/keboola/docker-bundle/pull/312/commits/d12be65d91685d98caa035308eaf80920f2952ac https://github.com/keboola/docker-bundle/pull/312/commits/629f7161ed6715ec4a1c0f82b5d0bb3e8e592d9b

ale nechces se me to presne pocitat, stejne bych se nedopocital, spokojim se s tim, ze to je 5% odchylka

**Comment by ondrejhlavacek** [comment]
🎉 🎉 🎉

**Pull request merged**
